# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'CCDropboxApp' do

pod 'AFNetworking', '~> 2.5'
pod 'Dropbox-iOS-SDK', '1.3.5'
pod 'MBProgressHUD', '~> 0.9'
#pod 'Dropbox-Sync-API-SDK', '~> 3.1'
end

# target 'CCDropboxAppTests' do

#end

